name: Node CI

on:
  pull_request:
    branches:
      - main
  push:
    tags:
      - '*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ '14', '16', '18' ]

    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2

      - name: Setup NodeJS
        uses: actions/setup-node@v3.4.1
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - name: Dependencies Install
        run: npm ci
        env:
          CI: true
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - name: Test
        run: npm run test
        env:
          CI: true
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - name: Codecov
        uses: codecov/codecov-action@v3.1.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true

  publish:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    strategy:
      matrix:
        node-version: [ '14' ]

    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2

      - name: Setup NodeJS
        uses: actions/setup-node@v3.4.1
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - name: Dependencies Install
        run: npm ci
        env:
          CI: true
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - name: Build
        run: npm run build:no-test:ci
        env:
          CI: true
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - name: Pre-Publish - install package globally
        run: |
          export VERSION=`node -e "console.log(require(""./package.json"").version)"`
          npm i -g fix-lockfile-integrity-%VERSION%.tgz
        shell: sh
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - name: Pre-Publish - test package globally
        run: |
          fix-lockfile-integrity
        shell: sh
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - name: Publish
        run: npm publish
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: fix-lockfile-integrity-*.tgz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
